import ProblemSetPageNavbar from "@/components/navbars/problemset-page-navbar/navbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProblemSetLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-backgroundBlack h-full">
      <div className="bg-lightGray/50 py-2">
        <ProblemSetPageNavbar />
      </div>
      {children}
    </div>
  );
}


