import ProblemSetPageNavbar from "@/components/problemset-page/navbar/navbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProblemSetLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="dark:bg-backgroundBlack  h-full min-h-svh w-full relative">
      <div className="dark:bg-lightGray/50 py-2 border-b-white/50 border-b mx-auto sticky top-0 bg-gray-200">
        <ProblemSetPageNavbar />
      </div>
      {children}
    </div>
  );
}
